# Application repository services.
#
# Note that these are only used with REST services.
services:
    repository:
        class: Doctrine\ORM\EntityRepository
        factory: [ '@doctrine.orm.entity_manager', getRepository ]
        shared: false

    repository.car_brand:
        parent: repository
        arguments: [ App\Entity\CarBrand ]
        class: App\Repository\CarBrand

    repository.date_dimension:
        parent: repository
        arguments: [ App\Entity\DateDimension ]
        class: App\Repository\DateDimension

    repository.offer:
        parent: repository
        arguments: [ App\Entity\Offer ]
        class: App\Repository\Offer

    repository.request_log:
        parent: repository
        arguments: [ App\Entity\RequestLog ]
        class: App\Repository\RequestLog

    repository.service:
        parent: repository
        arguments: [ App\Entity\Service ]
        class: App\Repository\Service

    repository.user:
        parent: repository
        arguments: [ App\Entity\User ]
        class: App\Repository\User

    repository.user_group:
        parent: repository
        arguments: [ App\Entity\UserGroup ]
        class: App\Repository\UserGroup

    repository.user_login:
        parent: repository
        arguments: [ App\Entity\UserLogin ]
        class: App\Repository\UserLogin

    repository.workshop:
        parent: repository
        arguments: [ App\Entity\Workshop ]
        class: App\Repository\Workshop
