services:
    app.controller.auth:
        class:      App\Controller\AuthController
        arguments:  [ '@security.token_storage', '@jms_serializer', '@app.services.rest.helper.response' ]

    app.controller.car_brand:
        class:      App\Controller\CarBrandController
        arguments:  [ '@app.services.rest.car_brand', '@app.services.rest.helper.response' ]

    app.controller.offer:
        class:      App\Controller\OfferController
        arguments:  [ '@app.services.rest.offer', '@app.services.rest.helper.response' ]

    app.controller.service_type:
        class:      App\Controller\ServiceTypeController
        arguments:  [ '@app.services.rest.service_type', '@app.services.rest.helper.response' ]

    app.controller.user:
        class:      App\Controller\UserController
        arguments:  [ '@app.services.rest.user', '@app.services.rest.helper.response' ]
        calls:
            - [ setTokenStorage, [ '@security.token_storage'] ]

    app.controller.user_group:
        class:      App\Controller\UserGroupController
        arguments:  [ '@app.services.rest.user_group', '@app.services.rest.helper.response' ]

    app.controller.workshop:
        class:      App\Controller\WorkshopController
        arguments:  [ '@app.services.rest.workshop', '@app.services.rest.helper.response' ]
