services:
    app.services.rest.helper.response:
        class: App\Services\Rest\Helper\Response
        arguments: [ '@serializer' ]

    app.services.rest.car_brand:
        class: App\Services\Rest\CarBrand
        arguments: [ '@repository.car_brand', '@validator' ]

    app.services.rest.offer:
        class: App\Services\Rest\Offer
        arguments: [ '@repository.offer', '@validator' ]
        calls:
          - [ setWorkshopService, [ '@app.services.rest.workshop' ] ]

    app.services.rest.request_log:
        class: App\Services\Rest\RequestLog
        arguments: [ '@repository.request_log', '@validator' ]

    app.services.rest.service_type:
        class: App\Services\Rest\ServiceType
        arguments: [ '@repository.service_type', '@validator' ]

    app.services.rest.user:
        class: App\Services\Rest\User
        arguments: [ '@repository.user', '@validator' ]

    app.services.rest.user_group:
        class: App\Services\Rest\UserGroup
        arguments: [ '@repository.user_group', '@validator' ]

    app.services.rest.user_login:
        class: App\Services\Rest\UserLogin
        arguments: [ '@repository.user_login', '@validator' ]

    app.services.rest.workshop:
        class: App\Services\Rest\Workshop
        arguments: [ '@repository.workshop', '@validator' ]
